id: P006918
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4459
  title: རྡོ་རྗེ་སེམས་དཔའ་ལ་བརྟེན་པའི་བླ་མ་མཆོད་པའི་ཆོ་ག་གཞན་ཕན་གྱི་ཕྲིན་ལས་དང་བཅས་པ་བདེ་ཆེན་ལམ་བཟང་།
  author: ''
  volumes:
    33369efe154f4e13a8a25cafed1ae405:
      image_group_id: I1KG4582
      title: ''
      volume_number: 1
      total_pages: 100
      base_file: v001.txt
