id: P006918
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4459
  title: རྡོ་རྗེ་སེམས་དཔའ་ལ་བརྟེན་པའི་བླ་མ་མཆོད་པའི་ཆོ་ག་གཞན་ཕན་གྱི་ཕྲིན་ལས་དང་བཅས་པ་བདེ་ཆེན་ལམ་བཟང་།
  author: ''
  volumes: {}
