id: I99D1FB7A
legacy_id: P006918
ocr_import_info:
  bdrc_scan_id: W1KG4459
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T16:14:29'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T16:40:59.555689+00:00'
last_modified: 2022-09-01 00:41:05.458774
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4459
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4459
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྡོ་རྗེ་སེམས་དཔའ་ལ་བརྟེན་པའི་བླ་མ་མཆོད་པའི་ཆོ་ག་གཞན་ཕན་གྱི་ཕྲིན་ལས་དང་བཅས་པ་བདེ་ཆེན་ལམ་བཟང་།
  author: མཁྱེན་བརྩེའི་དབང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.8659315173882337
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1KG4582:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4582
      total_pages: 100
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4582.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8659315173882337
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
