id: I99D1FB7A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:15:07+00:00'
last_modified: '2022-06-08T09:39:04.591682+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4459
  title: རྡོ་རྗེ་སེམས་དཔའ་ལ་བརྟེན་པའི་བླ་མ་མཆོད་པའི་ཆོ་ག་གཞན་ཕན་གྱི་ཕྲིན་ལས་དང་བཅས་པ་བདེ་ཆེན་ལམ་བཟང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4B07:
      image_group_id: I1KG4582
      title: ''
      total_pages: 100
      order: 1
      base_file: 4B07.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
